version: '3.9'
services:
  scraper:
    container_name: price_scraper
    build: .
    pull_policy: build
    ports:
      - 5000:5000
    volumes:
      - .:/opt/price_scraper/
    command: /opt/price_scraper/run.py
    restart: always

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  postgres-data:
