version: '3.9'
services:

  db:
    container_name: db
    image: postgres:16
    restart: unless-stopped
    env_file: db.conf
    # ports:
    #   - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  scraper:
    container_name: scraper
    build: .
    pull_policy: build ### Compose rebuilds image, even if one already exists
    restart: unless-stopped
    env_file: db.conf
    environment:
      POSTGRES_HOST: db
      FLASK_APP: /scraper/app.py
    ports:
      - 5000:5000
      - 5678:5678 ### debugpy
    volumes:
      - .:/scraper/
    command: flask run -h 0.0.0.0
    depends_on:
    - db

volumes:
  postgres-data:
