version: '3.9'
services:

  db:
    container_name: db
    image: postgres:latest
    restart: unless-stopped
    # environment:
    #   POSTGRES_USER: postgres
    #   POSTGRES_DB: postgres
    #   POSTGRES_PASSWORD: postgres
    env_file: db.conf
    # ports:
    #   - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  scraper:
    container_name: scraper
    build: .
    pull_policy: build ### Compose rebuilds image, even if one already exists
    restart: unless-stopped
    ports:
      - 5000:5000
    volumes:
      - .:/opt/price_scraper/
    command: /opt/price_scraper/run.py

volumes:
  postgres-data:
