version: '3.9'
services:

  db:
    container_name: db
    image: postgres:16.1-alpine3.19
    restart: unless-stopped
    env_file: db.conf
    volumes:
      - db:/var/lib/postgresql/data

  scraper:
    container_name: scraper
    build: .
    pull_policy: build ### Compose rebuilds image, even if one already exists
    restart: unless-stopped
    env_file: db.conf
    environment:
      FLASK_APP: /scraper/app.py
    ports:
      - 5000:5000
    volumes:
      - .:/scraper/
    command: flask run -h 0.0.0.0
    # command: python3 app.py run_app ### Moving init to function "run_app()"
    depends_on:
    - db

volumes:
  db:
