version: '3.9'
services:
  scraper:
    container_name: price_scraper
    build: .
    pull_policy: build
    ports:
      - 5000:5000
    volumes:
      - scraper_data:/opt/price_scraper/out/
    restart: always

volumes:
  scraper_data:
