# version: '3.9'
version: '3'
services:
  scraper:
    # container_name: scraper
    build: ./
    # build:
    #   context: ./
    #   dockerfile: Dockerfile
    image: my_scraper:latest ### Name:Tag of image to be built from Dockerfile
    ports:
      - 5000:5000
